theme: jekyll-theme-minimal
title: Dev Tools
description:  Welcome to my curated list of tech tools
logo: ./assets/logo.png
show_downloads: false
navigation:
  - title: Home
    url: /
  - title: - Javascript
    url: /#js
  - title: - CSS
    url: /#css
  - title: - Misc
    url: /#misc
  - title: Articles
    url: articles
  - title: Programming Languages
    url: languages
